# fly.toml app configuration file generated for howhotismal-influxdb on 2025-07-01T19:44:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'howhotismal-influxdb'
primary_region = 'bos'

[build]
  image = 'influxdb:2.7'

#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "influxdb_data"
  destination = "/var/lib/influxdb2"

# This section makes your InfluxDB instance public
[[services]]
  protocol = "tcp"
  internal_port = 8086 # The port InfluxDB runs on inside the container
  
  [[services.ports]]
    port = 443 # For public HTTPS traffic
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 80 # For public HTTP traffic
    handlers = ["http"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20
